import { makeDefaultVfo, BOOKMARK_CATEGORIES } from './constants';

export function createAppData() {
	return {
		backend: null as any,
		connected: false,
		running: false,
		isOnline: navigator.onLine,
		remoteMode: 'none' as 'none' | 'host' | 'client',
		remoteStatus: '',
		remoteLink: '',
		copyLinkSuccess: false,
		copyLinkTooltip: 'Copy link',
		remoteClients: [] as Array<{ id: string; connectedAt: number; country: string; vfoCount: number; firstFreq: number | null; isRelay: boolean }>,
		showRemoteClientsDialog: false,
		showRemoteConnectDialog: false,
		remoteConnectId: '',
		recentRemoteIds: [] as string[],
		remotePeerId: '',
		snackbar: { show: false, message: "" },
		audioUnlockPendingId: null as string | null,
		radio: {
			centerFreq: 100.0,
			sampleRate: 20000000,
			fftSize: 65536,
		},
		display: {
			minDB: -70.0,
			maxDB: 0.0,
		},
		gains: {} as Record<string, number>,
		deviceCapabilities: null as any,
		locks: {
			centerFreq: false,
			sampleRate: false,
		} as Record<string, boolean>,
		vfos: [makeDefaultVfo(100.0)],
		activeVfoIndex: 0,
		info: { boardName: "" },
		hoverFreqText: "",
		dspStats: null as any,
		showStats: false,
		fps: 0,
		vfoSquelchOpen: [] as boolean[],
		vfoSquelchHangUntil: [] as number[],
		vfoActivityStats: [] as Array<{ count: number; totalMs: number; squelchOpenSince: number | null }>,
		activityNow: 0,
		showActivity: false,
		view: {
			zoomScale: 1.0,
			zoomOffset: 0.0,
			locked: false
		},
		whisper: {
			panelOpen: false,
			active: false,
			status: 'idle' as string,
			loadProgress: 0,
			loadPhase: 'downloading' as string,
			loadFile: '',
			loadFilesDone: 0,
			loadFilesTotal: 0,
			model: 'onnx-community/whisper-small',
			chunkSeconds: 10,
			log: [] as Array<{ time: string; freq: string; text: string; duration: string; transcribeTime?: string; vfoIndex?: number | null }>,
			statusMsg: '',
			recording: false,
			transcribing: false,
			recordStart: null as Date | null,
			recordDuration: 0,
			pendingChunks: 0,
		},
		pocsag: {
			panelOpen: false,
			log: [] as Array<{ time: string; freq: string; vfoIndex: number; capcode: string; type: string; text: string; baud: number }>,
		},
		dsdStatus: [] as Array<{ mode: string; synced: boolean; syncName?: string; mbelibLoaded?: boolean; mbeDecoding?: boolean; mbeErrors?: string; voiceFrameCount?: number; colorCode?: number; slot?: number; slot0Burst?: string; slot1Burst?: string; nac?: number; duid?: string; src?: number; tg?: number; emr?: boolean; algid?: number; callsign?: string; nxdnType?: string } | null>,
		bookmarkCategories: BOOKMARK_CATEGORIES,
		bookmarkCategoryFilter: '',
		bookmarkSearch: '',
		bookmarks: [] as any[],
		bookmarkModal: { show: false, type: 'individual', name: '', category: '' },
		bookmarkImportModal: { show: false },
		bookmarkEdit: {
			show: false,
			index: -1,
			type: 'individual',
			name: '',
			category: '',
			// individual fields
			freq: 100.0,
			mode: 'nfm',
			bandwidth: 12500,
			snapInterval: 2500,
			deEmphasis: 'none',
			squelchEnabled: false,
			squelchLevel: -100,
			noiseReduction: false,
			stereo: false,
			lowPass: true,
			highPass: false,
			rds: false,
			rdsRegion: 'eu',
			volume: 50,
			// group fields
			centerFreq: 100.0,
			sampleRate: 8000000,
			vfos: [] as any[],
			activeVfoIndex: 0,
		},
		devicePicker: {
			show: false,
			devices: [] as Array<{ device: USBDevice; driverName: string; productName: string }>,
		},
		sidebarOpen: false,
		showAbout: false,
		collapsedPanels: {} as Record<string, boolean>,
		vfoConflictDialog: {
			show: false,
			vfoIndex: -1,
			requestedFreq: 0,
			previousFreq: 0,
			optionA: null as { centerFreq: number; description: string } | null,
			optionB: null as { centerFreq: number; description: string; excludedVfos: number[] } | null,
		},
	};
}
